// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["postgres://postgres:ykJDR1kAZeSqXMiAbDGvhIkGz48wxTS887gcIgB6uHspa3LFK0URpVJf4gixU5BY@g0g04gckgk448csocco80ows:5432/postgres"],
  },
});
